gazprom-neft/seismiqb

seismiqb/src/crop_batch.py
We should add a thread-safe caching mechanism later
=> Remove cache

pylintrc, scripts/horizon_report.py, seismiqb/src/crop_batch.py, seismiqb/src/cubeset.py, seismiqb/src/geometry.py, seismiqb/src/horizon.py, seismiqb/src/utils.py
This PR includes a method to make `float` predictions of horizons, as well as to average a number of them into one glorious surface.
Also, fixes a bug in `extension` grid generation.
=> Improvements

seismiqb/src/cubeset.py, seismiqb/src/fault.py, seismiqb/src/horizon.py, seismiqb/src/plotters.py, seismiqb/src/triangulation.py
Add tool to visualize 3D seismic data: slides, horizons, faults
=> Add 3D visualization

seismiqb/src/controllers/base.py, seismiqb/src/controllers/enhancer.py, seismiqb/src/controllers/extractor.py, seismiqb/src/controllers/horizon.py, seismiqb/src/controllers/interpolator.py, seismiqb/src/cubeset.py, seismiqb/src/horizon.py
Adds an option for fine-tuning the neural network for current chunk during inference
=> Add finetune procedure

seismiqb/src/cubeset.py, seismiqb/src/geometry/base.py, seismiqb/src/horizon.py
=> Fix show slide

seismiqb/src/crop_batch.py
If requested `component` is present in dataset and
is an instance of `IndexedDict` than return it.
Else retrieve it from batch attributes.
=> Change `CropBatch.get` behaviour

seismiqb/src/functional.py, seismiqb/src/metrics.py, seismiqb/src/utils/classes.py, setup.py
Use `bottleneck` and `numexpr` for faster computations
=> Speed up metrics

seismiqb/src/labels/horizon.py, seismiqb/src/labels/horizon_facies.py
Also update `fill_value` param retrieval in `Facies.load_attribute`
=> Make `Horizon.file_to_points` static to allow outer calls

seismiqb/src/labels/fault.py, seismiqb/src/utils/charisma.py, seismiqb/src/utils/functions.py
Fix transform of faults coordinates
=> Fix faults loading

seismiqb/src/utils/cache.py
`SEISMIQB_DISABLE_CACHE` env variable and fix methods retrieval
=> Cache improvements

seismiqb/field/visualization.py, seismiqb/geometry/export.py, seismiqb/plotters.py
* `show_3d` works with cubes without labels
* add slide bounds drawing
* fix `colorscale` and add colormaps from `matplotlib`
* small fix for `array_to_segy`
* add `camera` as a parameter
=> Show 3d update

seismiqb/labels/horizon_extraction.py
The extraction procedure was slowed down because of the updated reset.
=> Fix extraction

seismiqb/batch/visualization_batch.py, seismiqb/dataset.py, seismiqb/field/visualization.py, seismiqb/labels/horizon_visualization.py, seismiqb/samplers.py, seismiqb/utils/classes.py, tutorials/plot/02_slides.ipynb, tutorials/plot/04_batch.ipynb
Never hide mask zeros on plot if its a first subplot layer.
Never hide prediction values lower than 0.5 if its a first layer.
=> Change masks/predictions coloring in batch plot

seismiqb/denoising_metrics.py
metrics class for denoising performance estimation. contains source - prediction metrics for a batch, fourier power spectrum for an image, and local correlation and similarity maps for denoised image - estimated noise comparison.
=> created class for denoising metrics

pylintrc, seismiqb/batch/crop_batch.py, seismiqb/field/synthetic.py, seismiqb/functional/geometric_transforms.py, seismiqb/geometry/base.py, seismiqb/geometry/converted.py, seismiqb/labels/horizon/attributes.py, seismiqb/nn/utils.py, seismiqb/utils/accumulator3d.py, seismiqb/utils/charisma.py
- Fixes in `SyntheticField`
- Add `resize` for `SeismicCropBatch`
- Add dead traces computation in ` GeometryHDF5` defaults
- Add `show_slide_inference` method for models
- Add `np.uint8` conversion into `Accumulator3D`
=> Fixes and updates (`SyntheticField`, `SeismicCropBatch`, `GeometryHDF5`, `nn.utils`)

seismiqb/field/visualization.py, seismiqb/labels/fault/approximation.py, seismiqb/labels/fault/base.py, seismiqb/labels/fault/formats.py, seismiqb/labels/fault/postprocessing.py, seismiqb/labels/fault/surfaces_extractor.py, seismiqb/labels/fault/triangulation.py, seismiqb/labels/fault/visualization.py, seismiqb/plotters/show_3d.py
Changes in parameters of fault conversion procedures
=> Merge faults

seismiqb/geometry/base.py, seismiqb/labels/fault/surfaces_extractor.py
=> _connectivity_matrix is sparce

seismiqb/batch/crop_batch.py, seismiqb/labels/horizon/attributes.py, seismiqb/labels/horizon/base.py, seismiqb/utils/decorators.py
Remove unnecessary copies and fix bugs
=> Facies fixes

seismiqb/geometry/base.py, seismiqb/geometry/segy.py, seismiqb/labels/well/base.py, seismiqb/matching/collection.py, seismiqb/matching/well_seismic_tie.py
Initial well seismic matching. Description to be updated
=> Well seismic tie -> matching tools

seismiqb/geometry/utils.py, seismiqb/labels/horizon/horizon_extractor.py
* Sample (depth) to time conversion
* Add origin into horizon extractor
=> Small updates
